/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface OaiButton {
    /**
    * The minimum size
    */
    'state': 'default' | 'disabled' | 'pending';
  }
  interface OaiButtonAttributes extends StencilHTMLAttributes {
    /**
    * The minimum size
    */
    'state'?: 'default' | 'disabled' | 'pending';
  }

  interface OaiSideDrawer {}
  interface OaiSideDrawerAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MyComponent': Components.MyComponent;
    'OaiButton': Components.OaiButton;
    'OaiSideDrawer': Components.OaiSideDrawer;
  }

  interface StencilIntrinsicElements {
    'my-component': Components.MyComponentAttributes;
    'oai-button': Components.OaiButtonAttributes;
    'oai-side-drawer': Components.OaiSideDrawerAttributes;
  }


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLOaiButtonElement extends Components.OaiButton, HTMLStencilElement {}
  var HTMLOaiButtonElement: {
    prototype: HTMLOaiButtonElement;
    new (): HTMLOaiButtonElement;
  };

  interface HTMLOaiSideDrawerElement extends Components.OaiSideDrawer, HTMLStencilElement {}
  var HTMLOaiSideDrawerElement: {
    prototype: HTMLOaiSideDrawerElement;
    new (): HTMLOaiSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement
    'oai-button': HTMLOaiButtonElement
    'oai-side-drawer': HTMLOaiSideDrawerElement
  }

  interface ElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'oai-button': HTMLOaiButtonElement;
    'oai-side-drawer': HTMLOaiSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
