/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  Color,
} from './interface';
import {
  OAIDrawersStack,
} from './components/drawer/drawer-stack';
import {
  Segment,
} from './components/select/select';

export namespace Components {
  interface OaiButton {
    /**
    * (optional) The color of the button (pale / primary (default) / accent / error / warn)
    */
    'color'?: Color;
    /**
    * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
    */
    'download': string | undefined;
    /**
    * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered.
    */
    'href': string | undefined;
    /**
    * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
    */
    'rel': string | undefined;
    /**
    * (optional) The minimum size of the button (xs / sm / lg / xl) (optional) The type of the button (default = filled / outlined (stroked)) (optional) The state of the button (disabled / pending / undefined = default)
    */
    'state'?: 'disabled' | 'pending';
    /**
    * Specifies where to display the linked URL. Only applies when an `href` is provided. Special keywords: `"_blank"`, `"_self"`, `"_parent"`, `"_top"`.
    */
    'target': string | undefined;
  }
  interface OaiDrawer {
    'drawerStack': OAIDrawersStack;
    'inlineSize': string;
  }
  interface OaiDrawerStack {
    'pop': (payload?: any) => Promise<void>;
    'push': (name: string) => Promise<void>;
    'stack': string[];
  }
  interface OaiInclude {
    'src': string;
  }
  interface OaiLazyContent {}
  interface OaiProgressIndicator {
    'color'?: Color;
    /**
    * (optional) The size of the progress indicator (xs (default) / sm / lg / xl)
    */
    'size': 'xs' | 'sm' | 'lg' | 'xl';
  }
  interface OaiSelect {
    /**
    * (optional) auto expand selection (default = false)
    */
    'autoExpand': boolean;
    'condenseEnd': (i: number, offsetX: number) => Promise<void>;
    'condenseStart': (i: number, offsetX: number) => Promise<void>;
    'expandEnd': (i: number, offsetX: number) => Promise<void>;
    'expandStart': (i: number, offsetX: number) => Promise<void>;
    'segments': Segment[];
  }
  interface OaiSelectBind {
    'color': string;
    'index': number;
    'value': string | undefined;
  }
  interface OaiSelectResizer {}
  interface OaiToolbar {
    /**
    * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`. For more information on colors, see [theming](/docs/theming/basics).
    */
    'color'?: Color;
  }
}

declare global {


  interface HTMLOaiButtonElement extends Components.OaiButton, HTMLStencilElement {}
  var HTMLOaiButtonElement: {
    prototype: HTMLOaiButtonElement;
    new (): HTMLOaiButtonElement;
  };

  interface HTMLOaiDrawerElement extends Components.OaiDrawer, HTMLStencilElement {}
  var HTMLOaiDrawerElement: {
    prototype: HTMLOaiDrawerElement;
    new (): HTMLOaiDrawerElement;
  };

  interface HTMLOaiDrawerStackElement extends Components.OaiDrawerStack, HTMLStencilElement {}
  var HTMLOaiDrawerStackElement: {
    prototype: HTMLOaiDrawerStackElement;
    new (): HTMLOaiDrawerStackElement;
  };

  interface HTMLOaiIncludeElement extends Components.OaiInclude, HTMLStencilElement {}
  var HTMLOaiIncludeElement: {
    prototype: HTMLOaiIncludeElement;
    new (): HTMLOaiIncludeElement;
  };

  interface HTMLOaiLazyContentElement extends Components.OaiLazyContent, HTMLStencilElement {}
  var HTMLOaiLazyContentElement: {
    prototype: HTMLOaiLazyContentElement;
    new (): HTMLOaiLazyContentElement;
  };

  interface HTMLOaiProgressIndicatorElement extends Components.OaiProgressIndicator, HTMLStencilElement {}
  var HTMLOaiProgressIndicatorElement: {
    prototype: HTMLOaiProgressIndicatorElement;
    new (): HTMLOaiProgressIndicatorElement;
  };

  interface HTMLOaiSelectElement extends Components.OaiSelect, HTMLStencilElement {}
  var HTMLOaiSelectElement: {
    prototype: HTMLOaiSelectElement;
    new (): HTMLOaiSelectElement;
  };

  interface HTMLOaiSelectBindElement extends Components.OaiSelectBind, HTMLStencilElement {}
  var HTMLOaiSelectBindElement: {
    prototype: HTMLOaiSelectBindElement;
    new (): HTMLOaiSelectBindElement;
  };

  interface HTMLOaiSelectResizerElement extends Components.OaiSelectResizer, HTMLStencilElement {}
  var HTMLOaiSelectResizerElement: {
    prototype: HTMLOaiSelectResizerElement;
    new (): HTMLOaiSelectResizerElement;
  };

  interface HTMLOaiToolbarElement extends Components.OaiToolbar, HTMLStencilElement {}
  var HTMLOaiToolbarElement: {
    prototype: HTMLOaiToolbarElement;
    new (): HTMLOaiToolbarElement;
  };
  interface HTMLElementTagNameMap {
    'oai-button': HTMLOaiButtonElement;
    'oai-drawer': HTMLOaiDrawerElement;
    'oai-drawer-stack': HTMLOaiDrawerStackElement;
    'oai-include': HTMLOaiIncludeElement;
    'oai-lazy-content': HTMLOaiLazyContentElement;
    'oai-progress-indicator': HTMLOaiProgressIndicatorElement;
    'oai-select': HTMLOaiSelectElement;
    'oai-select-bind': HTMLOaiSelectBindElement;
    'oai-select-resizer': HTMLOaiSelectResizerElement;
    'oai-toolbar': HTMLOaiToolbarElement;
  }
}

declare namespace LocalJSX {
  interface OaiButton extends JSXBase.HTMLAttributes<HTMLOaiButtonElement> {
    /**
    * (optional) The color of the button (pale / primary (default) / accent / error / warn)
    */
    'color'?: Color;
    /**
    * This attribute instructs browsers to download a URL instead of navigating to it, so the user will be prompted to save it as a local file. If the attribute has a value, it is used as the pre-filled file name in the Save prompt (the user can still change the file name if they want).
    */
    'download'?: string | undefined;
    /**
    * Contains a URL or a URL fragment that the hyperlink points to. If this property is set, an anchor tag will be rendered.
    */
    'href'?: string | undefined;
    /**
    * Specifies the relationship of the target object to the link object. The value is a space-separated list of [link types](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types).
    */
    'rel'?: string | undefined;
    /**
    * (optional) The minimum size of the button (xs / sm / lg / xl) (optional) The type of the button (default = filled / outlined (stroked)) (optional) The state of the button (disabled / pending / undefined = default)
    */
    'state'?: 'disabled' | 'pending';
    /**
    * Specifies where to display the linked URL. Only applies when an `href` is provided. Special keywords: `"_blank"`, `"_self"`, `"_parent"`, `"_top"`.
    */
    'target'?: string | undefined;
  }
  interface OaiDrawer extends JSXBase.HTMLAttributes<HTMLOaiDrawerElement> {
    'drawerStack': OAIDrawersStack;
    'inlineSize'?: string;
  }
  interface OaiDrawerStack extends JSXBase.HTMLAttributes<HTMLOaiDrawerStackElement> {
    'onDrawerPopped'?: (event: CustomEvent<any>) => void;
    'stack'?: string[];
  }
  interface OaiInclude extends JSXBase.HTMLAttributes<HTMLOaiIncludeElement> {
    'src': string;
  }
  interface OaiLazyContent extends JSXBase.HTMLAttributes<HTMLOaiLazyContentElement> {}
  interface OaiProgressIndicator extends JSXBase.HTMLAttributes<HTMLOaiProgressIndicatorElement> {
    'color'?: Color;
    /**
    * (optional) The size of the progress indicator (xs (default) / sm / lg / xl)
    */
    'size'?: 'xs' | 'sm' | 'lg' | 'xl';
  }
  interface OaiSelect extends JSXBase.HTMLAttributes<HTMLOaiSelectElement> {
    /**
    * (optional) auto expand selection (default = false)
    */
    'autoExpand'?: boolean;
    'onTextSelected'?: (event: CustomEvent<any>) => void;
    'onUpdate'?: (event: CustomEvent<any>) => void;
    'segments'?: Segment[];
  }
  interface OaiSelectBind extends JSXBase.HTMLAttributes<HTMLOaiSelectBindElement> {
    'color': string;
    'index': number;
    'value'?: string | undefined;
  }
  interface OaiSelectResizer extends JSXBase.HTMLAttributes<HTMLOaiSelectResizerElement> {}
  interface OaiToolbar extends JSXBase.HTMLAttributes<HTMLOaiToolbarElement> {
    /**
    * The color to use from your application's color palette. Default options are: `"primary"`, `"secondary"`, `"tertiary"`, `"success"`, `"warning"`, `"danger"`, `"light"`, `"medium"`, and `"dark"`. For more information on colors, see [theming](/docs/theming/basics).
    */
    'color'?: Color;
  }

  interface IntrinsicElements {
    'oai-button': OaiButton;
    'oai-drawer': OaiDrawer;
    'oai-drawer-stack': OaiDrawerStack;
    'oai-include': OaiInclude;
    'oai-lazy-content': OaiLazyContent;
    'oai-progress-indicator': OaiProgressIndicator;
    'oai-select': OaiSelect;
    'oai-select-bind': OaiSelectBind;
    'oai-select-resizer': OaiSelectResizer;
    'oai-toolbar': OaiToolbar;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


